"""add billing fields to orders

Revision ID: 16dbb3d5edd1
Revises: 194b8aadafae
Create Date: 2026-06-17 12:01:26.802918
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '16dbb3d5edd1'
down_revision: Union[str, None] = '194b8aadafae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Helper to check index existence
    def index_exists(table, name):
        indexes = inspector.get_indexes(table)
        return any(idx['name'] == name for idx in indexes)
        
    # Helper to check column existence
    def column_exists(table, name):
        columns = inspector.get_columns(table)
        return any(c['name'] == name for c in columns)

    if not index_exists('categories', 'ix_categories_parent_id'):
        op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
        
    if not index_exists('order_items', 'ix_order_items_order_id'):
        op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
        
    if not index_exists('order_items', 'ix_order_items_product_id'):
        op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
        
    if not column_exists('orders', 'billing_cuit'):
        op.add_column('orders', sa.Column('billing_cuit', sa.String(length=11), nullable=True))
        
    if not column_exists('orders', 'billing_requested_at'):
        op.add_column('orders', sa.Column('billing_requested_at', sa.DateTime(), nullable=True))
        
    if not index_exists('orders', 'ix_orders_user_id'):
        op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
        
    try:
        op.drop_index('idx_products_fulltext', table_name='products', mysql_prefix='FULLTEXT')
    except Exception:
        pass
        
    if not index_exists('products', 'ix_products_category_id'):
        op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_index('idx_products_fulltext', 'products', ['nombre', 'descripcion'], unique=False, mysql_prefix='FULLTEXT')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_column('orders', 'billing_requested_at')
    op.drop_column('orders', 'billing_cuit')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    # ### end Alembic commands ###
