"""remove_cross_module_foreign_keys

Revision ID: 68770d84551a
Revises: da26ef9bbb9e
Create Date: 2026-06-25 22:43:57.882021
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '68770d84551a'
down_revision: Union[str, None] = 'da26ef9bbb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_2', 'orders', type_='foreignkey')
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_ibfk_1', 'orders', 'users', ['rider_id'], ['id'])
    op.create_foreign_key('orders_ibfk_2', 'orders', 'users', ['last_rider_id'], ['id'])
    # ### end Alembic commands ###
