"""add delivery fields

Revision ID: 8a9d4029e24a
Revises: 194b8aadafae
Create Date: 2026-06-02 17:42:44.817504
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8a9d4029e24a'
down_revision: Union[str, None] = '194b8aadafae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.add_column('order_items', sa.Column('producto_imagen_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.add_column('orders', sa.Column('rider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_rider_id'), 'orders', ['rider_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['rider_id'], ['id'])
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'orders', ['orden_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_rider_id'), table_name='orders')
    op.drop_column('orders', 'rider_id')
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_column('order_items', 'producto_imagen_url')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    # ### end Alembic commands ###
