"""add last_rider_id to orders

Revision ID: da26ef9bbb9e
Revises: 986ecc512068
Create Date: 2026-06-23 18:32:13.794705
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'da26ef9bbb9e'
down_revision: Union[str, None] = '986ecc512068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('last_rider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_last_rider_id'), 'orders', ['last_rider_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['last_rider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_last_rider_id'), table_name='orders')
    op.drop_column('orders', 'last_rider_id')
    # ### end Alembic commands ###
