"""add_intentos_to_orders

Revision ID: e7aa98997eb5
Revises: 31f16b8f7cd1
Create Date: 2026-06-22 18:08:10.310712
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e7aa98997eb5'
down_revision: Union[str, None] = '31f16b8f7cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('intentos', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['rider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'intentos')
    # ### end Alembic commands ###
